### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/sfdo-github#12]
The unnecessary test issue for proof. 

**lurch: add

**Comment by LurchTheButler** [comment]
Added: [W-007902](https://foundation--kbromer.cs30.my.salesforce.com/a2x560000004XOUAA2)

**Comment by LurchTheButler** [comment]
Tracking <a href="Url:[delegate=https://foundation--kbromer.cs42.my.salesforce.com]a2x560000004XfZAAU" target="_blank">W-008038</a>
