### ISSUE TITLE
Bromer Test Issue

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/sfdo-github#14]
**lurch: add

yada yada

**Comment by LurchTheButler** [comment]
Added: [W-007906](https://foundation--kbromer.cs30.my.salesforce.com/a2x560000004XQNAA2)

**Comment by kbromer** [comment]
<a href="http://example.com/" target="_blank">Hello, world!</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="Url:[delegate=https://foundation--kbromer.cs42.my.salesforce.com]a2x560000004XfWAAU" target="_blank">W-008035</a>
