### ISSUE TITLE
Another Bromer Test Issue

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/sfdo-github#15]
Here is another test. It includes important issue information.  

**lurch: add

**Comment by LurchTheButler** [comment]
Added: [W-007907](https://foundation--kbromer.cs30.my.salesforce.com/a2x560000004XQSAA2)

**Comment by LurchTheButler** [comment]
Tracking <a href="Url:[delegate=https://foundation--kbromer.cs42.my.salesforce.com]a2x560000004XfXAAU" target="_blank">W-008036</a>
