### ISSUE TITLE
Bromer Test Issues, continued...

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/sfdo-github#16]
Some very important information is what you'll find here. 

**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation--kbromer.cs30.my.salesforce.com/a2x560000004XQXAA2" target="_blank">W-007908</a>

**Comment by kbromer** [comment]
Now, here's a comment.

**Comment by kbromer** [comment]
Here's another comment.

**Comment by LurchTheButler** [comment]
Tracking <a href="Url:[delegate=https://foundation--kbromer.cs42.my.salesforce.com]a2x560000004XfaAAE" target="_blank">W-008039</a>
