### ISSUE TITLE
Bromer Test Issue

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/sfdo-github#17]
This is an issue 

**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="Url:[delegate=https://foundation--kbromer.cs42.my.salesforce.com]a2x560000004XfbAAE" target="_blank">W-008040</a>

**Comment by kbromer** [comment]
**lurch: detach

**Comment by LurchTheButler** [comment]
Tracking <a href="Url:[delegate=https://foundation--kbromer.cs42.my.salesforce.com]/a2x560000004XfbAAE" target="_blank">W-008040</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation--kbromer.cs42.my.salesforce.com/a2x560000004pKHAAY" target="_blank">W-008051</a>
