### ISSUE TITLE
Attach this one to an existing record

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/sfdo-github#19]
So starting here: 

**lurch: attach W-007902

**Comment by LurchTheButler** [comment]
Tracking <a href="Url:[delegate=https://foundation--kbromer.cs42.my.salesforce.com]a2x560000004XOUAA2" target="_blank">W-007902</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation--kbromer.cs42.my.salesforce.com/a2x560000004XOUAA2" target="_blank">W-007902</a>
