### ISSUE TITLE
This is an add from a comment

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/sfdo-github#22]
First the issue body

**Comment by kbromer** [comment]
now the comment

**lurch: add

**Comment by kbromer** [comment]
now another comment after the add comment

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation--kbromer.cs42.my.salesforce.com/a2x560000004pKJAAY" target="_blank">W-008053</a>

**Comment by kbromer** [comment]
**lurch: detach

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation--kbromer.cs42.my.salesforce.com/a2x560000004pKJAAY" target="_blank">W-008053</a>

**Comment by kbromer** [comment]
**lurch: attach W-008054

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation--kbromer.cs42.my.salesforce.com/a2x560000004pKWAAY" target="_blank">W-008054</a>
