### ISSUE TITLE
NicTest

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/sfdo-github#24]
foo;bar
**lurch: add

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation--kbromer.cs42.my.salesforce.com/a2x56000000572OAAQ" target="_blank">W-008058</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation--kbromer.cs42.my.salesforce.com/a2x56000000572SAAQ" target="_blank">W-008059</a>
