### ISSUE TITLE
See github links from work

### ISSUE THREAD

**Issue by lmeerkatz** [SalesforceFoundation/sfdo-github#4]
As a developer, I want to see linked Github records from related Work records.

Once github links are created, we'll want to see them from Work records. Since the only thing we can add to the page layout is custom fields, this will probably be a trigger-populated rollup field that aggregates all current links.

**Comment by kbromer** [comment]
Chatter?  This should be okay by @NickHBailey I think, since we're inside the walls...?

**Comment by lmeerkatz** [comment]
I'd like to have Chatter posts for the events (add/remove) as well as a field for what's currently linked so we don't have to dig through a feed. That part's optional.
